name: Deploy Project
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Uses checkout actions to 
    # download code on server
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS 
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
      # npm ci is safer and ensures dependencies
      # are in sync with package-lock.json
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    # runs in parallel unless needs: job_name
    needs: test
    runs-on: ubuntu-latest
    steps:
    # Uses checkout actions to 
    # download code on server
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS 
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project 
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."

