name: Output information
on: workflow_dispatch
jobs:
  info: 
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context 
        # GitHub is a reserved key-word
        run: echo "${{ toJSON(github) }}"